extends: standard

overrides:
  -
    files: [ '*.mjs' ]
    parserOptions:
      sourceType: module
    rules:
      no-restricted-globals: [ 2, require, __dirname ]

ignorePatterns:
  - coverage/
  - demo/
  - build/

rules:
  camelcase: 0
